# Generated by Django 5.1.1 on 2024-09-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userrolemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoleMapping',
        ),
    ]
